### ISSUE TITLE
Error with Node v20.14.0, but working properly Node 20.11.0

### ISSUE THREAD

**Issue by rjcmln** [fantonangeli/multi-clasp2#231]
**Command**: multi-clasp push

**Error with Node v20.14.0:**
1. CMD line output:
Elaborating scriptId: 1SQ4GFr_5sXG7h4p3DjUhjaW7iPaOrzmy-_t_Y0xS9pFXryFTsMzxxxxx _(1st scriptId in .multi-clasp.json file array)_

npm error could not determine executable to run

npm error A complete log of this run can be found in: C:\Users\xxx\AppData\Local\npm-cache\_logs\2024-06-24T16_57_10_576Z-debug-0.log

2. Log file
2024-06-24T16_57_10_576Z-debug-0.log
[2024-06-24T16_57_10_576Z-debug-0.log](https://github.com/user-attachments/files/15959363/2024-06-24T16_57_10_576Z-debug-0.log)

**With Node v20.11.0:**
No error, everything works, clasp is called, the scripts are updated

**OS**: Windows 10

**Comment by fantonangeli** [comment]
I don't have a Windows pc. Any help in testing this case is welcome.

**Comment by rjcmln** [comment]
I would like to help, please let me know how.

**Comment by fantonangeli** [comment]
Thank you so much @rjcmln.
Maybe you can try locally to change this line:
https://github.com/fantonangeli/multi-clasp2/blob/0430c99d6f850db0d51556ffb379662eded26f6c/src/common.ts#L25
to:
```ts
        const claspPath = path.resolve('node_modules', '.bin', process.platform === 'win32' ? 'clasp.cmd' : 'clasp');
        const { error, stdout, stderr } = await execShellCommand(`${claspPath} ${command} ${options}`);
```
and import:
```ts
import path from 'path';
```
removing `npx`. Maybe that is the executable which cannot be found by `child_process.exec()` .
I tested this fix on Linux with NodeJS v22.2.0 and it's working.

**Comment by rjcmln** [comment]
Sorry I can't test the exact case, I just changed my PC yesterday.

But I can confirm with fresh install, node, multi-clasp, win11... It works out of the box.
Node v22.11.0

Looks like you can close this issue.

**Comment by fantonangeli** [comment]
Thanks a lot @rjcmln, feel free to reopen it if you have this issue again.
