### ISSUE TITLE
[Request] Only Push and Update Selected File

### ISSUE THREAD

**Issue by LastRoze** [fantonangeli/multi-clasp2#3]
Case:

I have an app script that has 3 files across 5 sheets, with these file structures:

1. A.gs
2. B.gs
3. C.html

Now I want to update only A.gs and B.gs,  which I already prepared without C.html in my folder, whenever I multi-clasp push --force, the C.html in those 5 sheets is missing or deleted, which is not correct since I only push 2 files A and B gs.

Request:

Can we only push the files that we changed? because on those C.html will have different values needed for those 5 different sheets thank you.

**Comment by fantonangeli** [comment]
Hi @LastRoze , 
multi-clasp is simply a wrapper around the clasp command and does not have the capability to add new features to clasp.

The problem you reported is already documented in the clasp [README](https://github.com/google/clasp#push) and reported in this [issue](https://github.com/google/clasp/issues/762)

A possible workaround, if the structure of C.html is similar across the five sheets, is to store the data in one of the sheets of the spreadsheet and use placeholders inside C.html. You can render the HTML from GAS using libraries like React or jQuery, and hide and set permissions to the sheet with the data to prevent it from being visible to others.

I hope this helps you. Let me know if you have any further questions.
